# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Deniz Bayazit'
# tagline:          
# description:      'Hello! I am an incoming PhD student in CS @EPFL.'
url:              http://bayazitdeniz.github.io
baseurl:          /

author:
  name:           'Deniz Bayazit'
  # url:            

plugins: [jekyll-paginate]
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Custom vars
# version:          2.1.0
github:
  repo:           https://github.com/bayazitdeniz/bayazitdeniz.github.io

collections:
  pages:
    order:
      - /pages/about.md
      - /pages/pubs.md
      - /pages/teaching.md

exclude: [website.code-workspace]
